---
- name: glance-api process check
  sensu_process_check: service=glance-api
  notify: restart sensu-client

- name: glance-registry process check
  sensu_process_check: service=glance-registry
  notify: restart sensu-client

- name: glance-api check
  sensu_check: name=check-glance-api plugin=check-os-api.rb
               args="--service glance"
  notify: restart sensu-client

- name: glance-store check
  sensu_check: name=check-glance-store plugin=check-glance-store.py
  notify: restart sensu-client

- name: glance metrics
  template: src=etc/collectd/plugins/glance.conf dest=/etc/collectd/plugins/glance.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd
