---
- name: neutron process check
  sensu_process_check: service=neutron-server
  notify: restart sensu-client

- name: neutron free fips check
  sensu_check: name=check-neutron-free-fips plugin=check-neutron-fip.sh state=absent
  notify: restart sensu-client

- name: neutron free fips metrics check
  sensu_metrics_check: name=neutron-free-fips-metric plugin=check-neutron-fip.sh state=absent
  notify: restart sensu-client

- name: neutron metrics
  template: src=etc/collectd/plugins/neutron.conf dest=/etc/collectd/plugins/neutron.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd
