---
# not really a "horizon service" but horizon is the outlier
- name: restart horizon services
  service: name=apache2 state=restarted must_exist=false

- name: restart apache
  service: name=apache2 state=restarted must_exist=false

- name: compress horizon assets
  command: sudo -u www-data tools/with_venv.sh ./manage.py compress
           chdir=/opt/stack/horizon/
