---
dependencies:
  - role: ironic-common
  - role: nova-data
    nova:
      compute_driver: nova.virt.ironic.IronicDriver
      firewall_driver: nova.virt.firewall.NoopFirewallDriver
      scheduler_host_manager: nova.scheduler.ironic_host_manager.IronicHostManager
      compute_manager: ironic.nova.compute.manager.ClusteredComputeManager
