---
openstack_source:
  git_mirror: "{{ git_mirror|default('https://github.com/openstack') }}"
  pypi_mirror: "{{ pypi_mirror|default('https://pypi.python.org/simple/') }}"
  project_rev: "{{ project_rev|default('master') }}"
  git_update: no
  rootwrap: "{{ rootwrap|default(False)|bool }}"
