---
- name: swift-account service scripts
  template: src=roles/swift-common/templates/etc/init/swift-service.conf
            dest=/etc/init/swift-{{ item.service_name }}.conf mode=0644
  with_items:
    - { service_name: account-auditor, conf: account-server }
    - { service_name: account, conf: account-server }
    - { service_name: account-reaper, conf: account-server }
    - { service_name: account-replicator, conf: account-server }

- name: account-server config
  template: src=etc/swift/account-server.conf mode=0644
            dest=/etc/swift/account-server.conf owner=root group=root
  notify: restart swift-account service

- meta: flush_handlers

- name: start swift-account services
  service: name={{ item }} state=started
  with_items:
    - swift-account-auditor
    - swift-account-replicator
    - swift-account-reaper
    - swift-account
