---
- name: refresh cert auths
  command: update-ca-certificates

- name: restart logstash-forwarder
  service: name=logstash-forwarder state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
