---
- name: swift-container service scripts
  template: src=roles/swift-common/templates/etc/init/swift-service.conf
            dest=/etc/init/swift-{{ item.service_name }}.conf mode=0644
  with_items:
    - { service_name: container-auditor, conf: container-server }
    - { service_name: container, conf: container-server }
    - { service_name: container-replicator, conf: container-server }
    - { service_name: container-sync, conf: container-server }
    - { service_name: container-updater, conf: container-server }

- name: container-server config
  template: src=etc/swift/container-server.conf mode=0644
            dest=/etc/swift/container-server.conf owner=root group=root
  notify: restart swift-container service

- meta: flush_handlers

- name: start swift-container services
  service: name={{ item }} state=started
  with_items:
    - swift-container-replicator
    - swift-container-updater
    - swift-container-auditor
    - swift-container-sync
    - swift-container
